### Gaussian Mxiture Models 

= probabilistic model that assumes that the instances were generated from a mixture of several Gaussian distributions whose parameters are unknown. All instances generated from a single Gaussian distribution form a cluster with an ellipsoid shape. 

Dataset X is assumed to have been generated through a probabilistic process: 
 * For each instance, a cluster is picked randomly from among k clusters. The probability of choosing the $j^{(th)}$ cluster is defined by the cluster's weight $\phi^{(i)}$. The index of the cluster chosen for the $i^{(th)}$ instance is noted $z^{(i)}$
 * If $z^{(i)}$ = $j$ --> the $i^{(th)}$ instance has been assigned to the $j^{(th)}$ cluster and the location $x^{(i)}$ of this instance is sampled randomly from the Gaussian distribution with mean $\mu^{(j)}$ and covariance matrix $\Sigma^{(j)}$.

In [1]:
from sklearn.datasets import load_iris 

iris = load_iris()
X = iris.data
y = iris.target


In [2]:
from sklearn.mixture import GaussianMixture 

gm = GaussianMixture(n_components = 3, n_init = 10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [3]:
gm.weights_

array([0.36548058, 0.33333333, 0.30118609])

In [4]:
gm.means_

array([[6.54632887, 2.94943079, 5.4834877 , 1.98716063],
       [5.006     , 3.428     , 1.462     , 0.246     ],
       [5.91697517, 2.77803998, 4.20523542, 1.29841561]])

In [5]:
gm.covariances_

array([[[0.38741443, 0.09223101, 0.30244612, 0.06089936],
        [0.09223101, 0.11040631, 0.08386768, 0.0557538 ],
        [0.30244612, 0.08386768, 0.32595958, 0.07283247],
        [0.06089936, 0.0557538 , 0.07283247, 0.08488025]],

       [[0.121765  , 0.097232  , 0.016028  , 0.010124  ],
        [0.097232  , 0.140817  , 0.011464  , 0.009112  ],
        [0.016028  , 0.011464  , 0.029557  , 0.005948  ],
        [0.010124  , 0.009112  , 0.005948  , 0.010885  ]],

       [[0.27550587, 0.09663458, 0.18542939, 0.05476915],
        [0.09663458, 0.09255531, 0.09103836, 0.04299877],
        [0.18542939, 0.09103836, 0.20227635, 0.0616792 ],
        [0.05476915, 0.04299877, 0.0616792 , 0.03232217]]])

The weights, means and covariances are computed using Expectation-Maximization: 
 * Initialize the cluster parameters randomly (**expectation**) 
 * Update the clusters (**maximization**) 
 
--> generalization of K-Means that not only finds the cluster centers $\mu^{(1)}$ to $\mu^{(k)}$, but also their size, shape and orientation (specified by the covariance matrices $\Sigma^{(1)}$ to $\Sigma^{(k)}$) as well as their relative weights $\phi^{(1)}$ to $\phi^{(k)}$. 

Uses soft cluster assignments: 
 * during the expectation step, the algorithm estimates the probability that the instance belongs to each cluster 
 * during the maximization step, each cluster is updated using all the instances in the dataset, with each instance weighted by the estimated probability that it belongs to that cluster. 
 
Probabilities are called **responsibilities** of the clusters for the instances. 

**!** Like K-Means, EM can converge to local optima, so it needs to be run several times (set *n_init* hyperparamenter to at least 10 because the default is actually 1) 

In [6]:
gm.converged_

True

In [7]:
gm.n_iter_

17

In [8]:
gm.predict(X)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
gm.predict_proba(X)

array([[6.39829159e-035, 1.00000000e+000, 9.06516804e-044],
       [2.59954184e-028, 1.00000000e+000, 8.53836828e-031],
       [4.21198692e-030, 1.00000000e+000, 9.37295905e-036],
       [2.71194113e-026, 1.00000000e+000, 1.46701195e-031],
       [2.68318787e-035, 1.00000000e+000, 3.36751068e-046],
       [3.36012794e-035, 1.00000000e+000, 8.48608974e-045],
       [6.26078635e-029, 1.00000000e+000, 8.60802283e-036],
       [6.24083932e-032, 1.00000000e+000, 5.91440044e-040],
       [2.73560964e-024, 1.00000000e+000, 2.15420817e-027],
       [9.44427381e-029, 1.00000000e+000, 1.98301504e-035],
       [6.19144802e-038, 1.00000000e+000, 3.71910256e-049],
       [3.03045219e-029, 1.00000000e+000, 1.87444991e-038],
       [2.07458621e-028, 1.00000000e+000, 1.18922833e-033],
       [7.36953464e-028, 1.00000000e+000, 4.60969420e-034],
       [3.91524413e-048, 1.00000000e+000, 4.30870613e-062],
       [1.43839472e-046, 1.00000000e+000, 2.57581224e-063],
       [3.26910339e-040, 1.00000000e+000

Gaussian Mixture model is a **generative model**, meaning that we can sample new instances from it. 

In [10]:
X_new, y_new = gm.sample(6)

In [11]:
X_new

array([[6.30846601, 3.28091339, 5.77954139, 2.17222942],
       [6.58123773, 2.73152551, 5.23339158, 2.02313703],
       [5.04105261, 3.85046066, 1.4492698 , 0.35114666],
       [5.3938198 , 4.09761375, 1.5151537 , 0.35198595],
       [4.44844668, 2.65745851, 1.30331639, 0.14075086],
       [6.37004193, 3.1979007 , 4.28993066, 1.38915008]])

In [12]:
y_new

array([0, 0, 1, 1, 1, 2])

It is also possible to estimate the density of the model at any given location with the *score_samples()* method. For each instance, this method estimates the log of the probability density function at that location --> the greater the score, the higher the density. 

In [13]:
gm.score_samples(X)

array([ 1.57050082,  0.73787138,  1.14436656,  0.92913238,  1.411028  ,
       -0.09451903,  0.05266884,  1.62442195,  0.27082378,  0.16706624,
        0.83489877,  0.77168582,  0.29597841, -1.79224582, -3.41557928,
       -2.10529279, -1.12995447,  1.47503579, -0.84612536,  0.97699215,
       -0.92934784,  0.41079066, -3.83509616, -1.88906058, -3.17355662,
       -0.12403068,  0.51111724,  1.37663152,  1.12464925,  0.69029112,
        0.78206572, -0.69467132, -2.12834347, -0.8778815 ,  1.153231  ,
        0.11508687, -1.11928741,  0.22543724,  0.13115634,  1.49896403,
        0.94007659, -4.48978774, -0.34371496, -4.48037212, -2.58855877,
        0.67996207,  0.3937127 ,  1.04001332,  1.16051416,  1.54721281,
       -2.04219856, -0.26690497, -0.85097585, -2.32641778, -1.1625818 ,
       -0.79356973, -0.81650435, -1.40144428, -0.44903274, -1.64498537,
       -2.59281522, -0.60402676, -2.52104033, -0.11016408, -1.92916117,
       -1.15964891, -1.27337947, -2.94118443, -5.17236275,  0.26

We can reduce the difficulty of the learning task by limiting the number of parameters that the algorithm has to learn --> limit the range of shapes and orientations that the clusters can have by imposing constraints on the covariance matrices:
 * *covariance_type* = **"spherical"**, which means that all clusters must be spherical but have different diameters (variances) 
 * *covariance_type* = **"diag"**, which means that clusters can take any ellipsoidal shape of any size but the axes must be parallel to the coordinate axes (covariance matrices must be diagonal) 
 * *covariance_type* = **"tied"**, which means that clusters have the same ellipsoidal shape, size and orientation (same covariance matrix for all) 
 * *covariance_type* = **"full"**, which means that clusters can take on any shape, size and orientation (this is the default) 

#### Anomaly detection using Gaussian Mixtures 

Any instance located in a low-density region can be considered an anomaly. Define the density threshold. 

In [15]:
densities = gm.score_samples(X)
import numpy as np
density_threshold = np.percentile(densities, 4)
anomalies = X[densities < density_threshold]

In [16]:
anomalies

array([[4.5, 2.3, 1.3, 0.3],
       [6.2, 2.2, 4.5, 1.5],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [7.9, 3.8, 6.4, 2. ],
       [6.1, 2.6, 5.6, 1.4]])

#### Selecting the number of clusters

Find the model that minimizes a theoretical information criterion: 
 * Bayesian Information Criterion (BIC) = $log(m)p - 2 log(\hat{L})$
 * Akaike Information Criterion (AIC) = $2p - 2 log(\hat{L})$ 

where: 
 * m is the number of instances 
 * p is the number of parameters learned by the model 
 * $\hat{L}$ maximized value of the likelihood function of the model 

Both BIC and AIC penalize models that have more parameters to learn and reward models that fit the data well. 
Difference: model selected by BIC tend to be simpler that the one selected by AIC, but tends not to fit the data as well. 

**Likelihood function** 

Given a statistical model with some parameters $\theta$:
 * *probability* is used to describe how plausible a future outcome $x$ is knowing the parameter values --> probability density function is a function of $x$ with $\theta$ fixed 
 * *likelihood* is used to describe how plausible a particular set of parameter values is after the outcome $x$ is known --> likelihood function is a function of $\theta$ with $x$ fixed 
 

Given a dataset X, we want to estimate the most likely values for the model parameters. To do this, we find the values that maximize the likelihood function given X. 

In [17]:
gm.bic(X)

580.8594247694392

In [18]:
gm.aic(X)

448.39147182920397

#### Bayesian Gaussian Mixture Models 

BayesianGaussianMixture class is capable of giving weights equal or close to zero to unnecessary clusters. We set the number of clusters *n_components* to a value which we have reason to believe is greater than the optimal number of clusters and then the algorithm eliminates the unnecessary clusters automatically. 

In [19]:
from sklearn.mixture import BayesianGaussianMixture 

bgm = BayesianGaussianMixture(n_components = 10, n_init = 10)
bgm.fit(X)
np.round(bgm.weights_, 2)

array([0.06, 0.34, 0.19, 0.41, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ])

In this model, the cluster parameters (weights, means and covariance matrices) are treated as latent random variables. **Beta distribution** is commonly used to model random variables whose values lie within a fixed range (0 to 1). 

**Prior knowledge** about latent variables z is encoded in a probability distribution $p(z)$ called the prior. **Bayes theorem** tells how to update the probability distribution over the latent variables after we observe some data X. It computes the **posterior distribution** $p(z|X)$ which is the conditional probability of z given X. 

$p(z|X)$ = posterior = $\frac{likelihood x prior}{evidence}$ = $\frac{p(X|z) p(z)}{p(X)}$

In a Gaussian mixture model, the denominator p(X) is intractable as it requires integrating over all the possible values of z (considering all possible combinations of cluster parameters and cluster assignments). 
--> approaches to solve the intractability of the evidence: 
 * **variational inference** = picks a family of distributions q(z; $\lambda$) with its own variational parameters $\lambda$ and then optimizes these parameters to make q(z) a good approximation of p(z|X). This is achieved by finding the value of $\lambda$ which minimizes the KL divergence from q(z) to p(z|X). 

#### Other algorithms for anomaly and novelty detection 

* **PCA** = if we compare the reconstruction error of a normal instance with the reconstruction error of an anomaly, the latter will usually be much larger. 
* **Fast Minimum Covariance Determinant** = assumes that the normal instances are generated from a single Gaussian distribution and assumes that the data is contaminated with outliers that were not generated from this Gaussian distribution. (implemented in the EllipticEnvelope class) 
* **Isolation Forest** = builds a Random Forest in which each decision tree is grown randomly --> anomalies are usually far from other instances so they tend to be isolated in fewer steps than normal instances. 
* **Local Outlier Factor** = compares the density of instances around a given instance to the density around its neighbors. 
* **One-class SVM** = tries to separate the instances in a high dimensional space fromm the origin. 

#### End of notebook 